package com.iud.vista;

import com.iud.datos.CbHelper;
import java.time.LocalTime;
import java.time.temporal.ChronoUnit;

/**
 *
 * @author Berserk
 */
public class pagoVista extends javax.swing.JFrame {
    final String seleccione = "Seleccione una opcion";
    CbHelper cb = new CbHelper();

    /**
     * Creates new form pagoVista
     */
    public pagoVista() {
        initComponents();
        cb.consultarPlacaSalida(cbxPlaca);
        txtPlaca.setVisible(false);
        //txtTotal.setVisible(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jDialog1 = new javax.swing.JDialog();
        jPanel2 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        lblTotal = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        lblMinutos = new javax.swing.JLabel();
        lblPlaca = new javax.swing.JLabel();
        lblIngreso = new javax.swing.JLabel();
        lblSalida = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        cbxPlaca = new javax.swing.JComboBox<>();
        jLabel1 = new javax.swing.JLabel();
        txtPlaca = new javax.swing.JTextField();
        txtIngreso = new javax.swing.JTextField();
        txtSalida = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        btnPagar = new javax.swing.JButton();
        txtTotal = new javax.swing.JTextField();

        jDialog1.setMinimumSize(new java.awt.Dimension(400, 300));
        jDialog1.setModal(true);
        jDialog1.setPreferredSize(new java.awt.Dimension(400, 300));
        jDialog1.setResizable(false);
        jDialog1.setSize(new java.awt.Dimension(400, 300));

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setMinimumSize(new java.awt.Dimension(400, 300));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel4.setBackground(new java.awt.Color(0, 0, 0));
        jLabel4.setText("PARQUEADERO AUTOS COLOMBIA");
        jPanel2.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 40, -1, -1));

        jLabel5.setText("Total a Pagar:");
        jPanel2.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 230, -1, -1));

        jLabel6.setText("Factura de Venta");
        jPanel2.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 10, -1, -1));

        jLabel7.setText("Valor por minuto $50 pesos");
        jPanel2.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 60, -1, -1));

        jLabel8.setText("Hora de ingreso:");
        jPanel2.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 130, -1, -1));

        jLabel9.setText("Hora de salida:");
        jPanel2.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 160, -1, -1));

        jLabel10.setText("Placa del vehiculo:");
        jPanel2.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 100, -1, -1));

        jLabel11.setText("Cantidad de minutos:");
        jPanel2.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 190, -1, -1));

        lblTotal.setFont(new java.awt.Font("Sitka Small", 0, 12)); // NOI18N
        lblTotal.setForeground(new java.awt.Color(255, 0, 51));
        jPanel2.add(lblTotal, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 230, 70, 20));

        jLabel12.setForeground(new java.awt.Color(255, 0, 51));
        jLabel12.setText("$");
        jPanel2.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 230, 10, -1));

        lblMinutos.setFont(new java.awt.Font("Sitka Small", 0, 12)); // NOI18N
        jPanel2.add(lblMinutos, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 190, 100, 20));

        lblPlaca.setFont(new java.awt.Font("Sitka Small", 0, 12)); // NOI18N
        jPanel2.add(lblPlaca, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 100, 100, 20));

        lblIngreso.setFont(new java.awt.Font("Sitka Small", 0, 12)); // NOI18N
        jPanel2.add(lblIngreso, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 130, 100, 20));

        lblSalida.setFont(new java.awt.Font("Sitka Small", 0, 12)); // NOI18N
        jPanel2.add(lblSalida, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 160, 100, 20));

        javax.swing.GroupLayout jDialog1Layout = new javax.swing.GroupLayout(jDialog1.getContentPane());
        jDialog1.getContentPane().setLayout(jDialog1Layout);
        jDialog1Layout.setHorizontalGroup(
            jDialog1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 400, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        jDialog1Layout.setVerticalGroup(
            jDialog1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setMinimumSize(new java.awt.Dimension(600, 400));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        cbxPlaca.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        cbxPlaca.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbxPlacaActionPerformed(evt);
            }
        });
        jPanel1.add(cbxPlaca, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 70, 120, -1));

        jLabel1.setText("PLACA");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 40, -1, -1));

        txtPlaca.setEditable(false);
        jPanel1.add(txtPlaca, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 40, -1, -1));

        txtIngreso.setEditable(false);
        jPanel1.add(txtIngreso, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 150, 140, -1));

        txtSalida.setEditable(false);
        jPanel1.add(txtSalida, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 150, 140, -1));

        jLabel2.setText("HORA DE INGRESO");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 120, -1, -1));

        jLabel3.setText("HORA DE SALIDA");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 120, -1, -1));

        btnPagar.setText("PAGAR");
        btnPagar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnPagarMouseClicked(evt);
            }
        });
        jPanel1.add(btnPagar, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 150, 110, -1));

        txtTotal.setEditable(false);
        txtTotal.setMinimumSize(new java.awt.Dimension(64, 80));
        jPanel1.add(txtTotal, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 70, 110, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 622, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 400, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cbxPlacaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbxPlacaActionPerformed
        String placaElegida;
        LocalTime horaIngreso, horaSalida;
        long mins, valor;

        if (cbxPlaca.getSelectedItem() != null) {
            if (cbxPlaca.getSelectedItem() != seleccione) {
                placaElegida = cbxPlaca.getSelectedItem().toString();
                txtPlaca.setText(placaElegida);
                cb.consultarRegistrosPago(txtIngreso, txtSalida, placaElegida);
                horaIngreso = LocalTime.parse(txtIngreso.getText());
                horaSalida = LocalTime.parse(txtSalida.getText());
                System.out.println("hora de ingreso: "+ horaIngreso);
                System.out.println("hora de salida: "+ horaSalida);
                mins = ChronoUnit.MINUTES.between(horaIngreso, horaSalida);
                System.out.println("diferencia: " + mins);
                valor = mins *50;
                System.out.println("Valor a pagar: " + valor);
                txtTotal.setText(String.valueOf((valor)));
                lblTotal.setText(String.valueOf((valor)));
                lblPlaca.setText(placaElegida);
                lblIngreso.setText(txtIngreso.getText());
                lblSalida.setText(txtSalida.getText());
                lblMinutos.setText(String.valueOf(mins));
               
            }else{
                txtPlaca.setText("");
            }
        }
    }//GEN-LAST:event_cbxPlacaActionPerformed

    private void btnPagarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnPagarMouseClicked
        
        jDialog1.setVisible(true);
    }//GEN-LAST:event_btnPagarMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(pagoVista.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(pagoVista.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(pagoVista.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(pagoVista.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new pagoVista().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnPagar;
    private javax.swing.JComboBox<String> cbxPlaca;
    private javax.swing.JDialog jDialog1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JLabel lblIngreso;
    private javax.swing.JLabel lblMinutos;
    private javax.swing.JLabel lblPlaca;
    private javax.swing.JLabel lblSalida;
    private javax.swing.JLabel lblTotal;
    private javax.swing.JTextField txtIngreso;
    private javax.swing.JTextField txtPlaca;
    private javax.swing.JTextField txtSalida;
    private javax.swing.JTextField txtTotal;
    // End of variables declaration//GEN-END:variables
}
