package com.iud.vista;

import com.iud.dao.RegistroDao;
import com.iud.datos.CbHelper;
import com.iud.modelo.Registro;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Berserk
 */
public class VistaRegistro extends javax.swing.JFrame {
    String columnas[]={"ID REGISTRO", "AÑO", "MES", "DIA", "PLACA", "CEDULA PROPIETARIO", "VALOR MENSUALIDAD"};
    DefaultTableModel modelo = new DefaultTableModel(columnas, 0);
    ArrayList<Object[]> data = new ArrayList<>();
    RegistroDao registroDao = new RegistroDao();
    CbHelper cb = new CbHelper();
    
    public VistaRegistro() {
        initComponents();
        cargar();
        cb.consultarCedula(cmbCedula);
        cb.consultarPlaca(cmbPlaca);
    }
    
    private void cargar(){
        this.data = registroDao.consultar();
        modelo.setNumRows(0);
        for(Object [] dato : this.data){
            this.modelo.addRow(dato);
        }
        tblRegistro.setModel(modelo);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblRegistro = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        txtId = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        txtAno = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        txtMensualidad = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        txtDia = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        cmbCedula = new javax.swing.JComboBox<>();
        jLabel7 = new javax.swing.JLabel();
        cmbPlaca = new javax.swing.JComboBox<>();
        jLabel8 = new javax.swing.JLabel();
        txtMes = new javax.swing.JTextField();
        btnLimpiar = new javax.swing.JButton();
        btnAgregar = new javax.swing.JButton();
        btnEliminar = new javax.swing.JButton();
        btnModificar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        tblRegistro.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tblRegistro.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblRegistroMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tblRegistro);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(2, 280, 960, 230));

        jLabel1.setText("ID");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 50, 30, -1));

        txtId.setEditable(false);
        jPanel1.add(txtId, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 70, 100, -1));

        jLabel2.setText("FECHA DE CREACION");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 10, -1, -1));

        jLabel3.setText("CEDULA");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 120, 70, -1));
        jPanel1.add(txtAno, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 70, 80, -1));

        jLabel4.setText("VALOR MENSUALIDAD");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 210, 130, -1));
        jPanel1.add(txtMensualidad, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 240, 190, -1));

        jLabel5.setText("DIA:");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 40, 50, -1));
        jPanel1.add(txtDia, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 70, 80, -1));

        jLabel6.setText("AÑO:");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 40, 70, -1));

        cmbCedula.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        jPanel1.add(cmbCedula, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 150, 230, -1));

        jLabel7.setText("PLACA");
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 120, 70, -1));

        cmbPlaca.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        jPanel1.add(cmbPlaca, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 150, 220, -1));

        jLabel8.setText("MES:");
        jPanel1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 40, 50, -1));
        jPanel1.add(txtMes, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 70, 90, -1));

        btnLimpiar.setText("Limpiar");
        btnLimpiar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnLimpiarMouseClicked(evt);
            }
        });
        btnLimpiar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLimpiarActionPerformed(evt);
            }
        });
        jPanel1.add(btnLimpiar, new org.netbeans.lib.awtextra.AbsoluteConstraints(790, 140, -1, -1));

        btnAgregar.setText("Agregar");
        btnAgregar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnAgregarMouseClicked(evt);
            }
        });
        jPanel1.add(btnAgregar, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 50, -1, -1));

        btnEliminar.setText("Eliminar");
        btnEliminar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnEliminarMouseClicked(evt);
            }
        });
        jPanel1.add(btnEliminar, new org.netbeans.lib.awtextra.AbsoluteConstraints(790, 50, -1, -1));

        btnModificar.setText("Modificar");
        btnModificar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnModificarMouseClicked(evt);
            }
        });
        jPanel1.add(btnModificar, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 140, -1, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 970, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 529, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnLimpiarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLimpiarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnLimpiarActionPerformed

    private void tblRegistroMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblRegistroMouseClicked
        txtId.setText(tblRegistro.getValueAt(tblRegistro.getSelectedRow(), 0).toString());
        txtAno.setText(tblRegistro.getValueAt(tblRegistro.getSelectedRow(), 1).toString());
        txtMes.setText(tblRegistro.getValueAt(tblRegistro.getSelectedRow(), 2).toString());
        txtDia.setText(tblRegistro.getValueAt(tblRegistro.getSelectedRow(), 3).toString());
        cmbPlaca.setSelectedItem(tblRegistro.getValueAt(tblRegistro.getSelectedRow(), 4));
        cmbCedula.setSelectedItem(tblRegistro.getValueAt(tblRegistro.getSelectedRow(), 5));
        txtMensualidad.setText(tblRegistro.getValueAt(tblRegistro.getSelectedRow(), 6).toString());
    }//GEN-LAST:event_tblRegistroMouseClicked

    private void btnLimpiarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnLimpiarMouseClicked
        txtId.setText("");
        txtAno.setText("");
        txtMes.setText("");
        txtDia.setText("");
        cmbPlaca.setSelectedIndex(0);
        cmbCedula.setSelectedIndex(0);
        txtMensualidad.setText("");
    }//GEN-LAST:event_btnLimpiarMouseClicked

    private void btnAgregarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnAgregarMouseClicked
        String selPlaca=(String) cmbPlaca.getSelectedItem();
        Integer selCedula=(Integer) cmbCedula.getSelectedItem();
      
        
        Registro registro = new Registro(Integer.parseInt(txtAno.getText()),
                                      Integer.parseInt(txtMes.getText()),
                                      Integer.parseInt(txtDia.getText()),
                                      selPlaca.toString(),
                                      selCedula,
                                      Integer.parseInt(txtMensualidad.getText()));
        if(registroDao.insertar(registro)){
            JOptionPane.showMessageDialog(this, "Se a agregado correcatamente!!!");
        }else{
            JOptionPane.showMessageDialog(this, "Error al agregar...");
        }
        cargar();
       
    }//GEN-LAST:event_btnAgregarMouseClicked

    private void btnModificarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnModificarMouseClicked
        String selPlaca=(String) cmbPlaca.getSelectedItem();
        Integer selCedula=(Integer) cmbCedula.getSelectedItem();
        
        Registro registro = new Registro(Integer.parseInt(txtAno.getText()),
                                      Integer.parseInt(txtMes.getText()),
                                      Integer.parseInt(txtDia.getText()),
                                      selPlaca.toString(),
                                      selCedula,
                                      Integer.parseInt(txtMensualidad.getText()));
        if(registroDao.modificar(registro)){
            JOptionPane.showMessageDialog(this, "Se a agregado correcatamente!!!");
        }else{
            JOptionPane.showMessageDialog(this, "Error al agregar...");
        }
        cargar();
    }//GEN-LAST:event_btnModificarMouseClicked

    private void btnEliminarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnEliminarMouseClicked
        String selPlaca=(String) cmbPlaca.getSelectedItem();
        Integer selCedula=(Integer) cmbCedula.getSelectedItem();
        
        Registro registro = new Registro(Integer.parseInt(txtId.getText()),
                                      Integer.parseInt(txtAno.getText()),
                                      Integer.parseInt(txtMes.getText()),
                                      Integer.parseInt(txtDia.getText()),
                                      selPlaca.toString(),
                                      selCedula,
                                      Integer.parseInt(txtMensualidad.getText()));
        if(registroDao.eliminar(registro)){
            JOptionPane.showMessageDialog(this, "Se a agregado correcatamente!!!");
        }else{
            JOptionPane.showMessageDialog(this, "Error al agregar...");
        }
        cargar();
    }//GEN-LAST:event_btnEliminarMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VistaRegistro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VistaRegistro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VistaRegistro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VistaRegistro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new VistaRegistro().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAgregar;
    private javax.swing.JButton btnEliminar;
    private javax.swing.JButton btnLimpiar;
    private javax.swing.JButton btnModificar;
    private javax.swing.JComboBox<String> cmbCedula;
    private javax.swing.JComboBox<String> cmbPlaca;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tblRegistro;
    private javax.swing.JTextField txtAno;
    private javax.swing.JTextField txtDia;
    private javax.swing.JTextField txtId;
    private javax.swing.JTextField txtMensualidad;
    private javax.swing.JTextField txtMes;
    // End of variables declaration//GEN-END:variables
}
